import type { Meta, StoryObj } from '@storybook/react';

import { StationCard } from '@/components/map';

const meta = {
  title: 'Example/StationCard',
  component: StationCard,
} satisfies Meta<typeof StationCard>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    item: {
      station: {
        arsId: '02137',
        stationName: '서울신문사',
        nextStationName: 'KT광화문지사',
        crowding: 'EASYGOING',
        xlatitude: 126.977364705,
        ylongitude: 37.5683632936,
      },
      busList: [
        {
          direction: 'KT광화문지사',
          firstArrivalBusTime: 0,
          secondArrivalBusTime: 0,
          firstArrivalBusCrowding: 'NODATA',
          secondArrivalBusCrowding: 'NODATA',
          firstArrivalTimeBefore: 'NODATA',
          secondArrivalTimeBefore: 'NODATA',
          busId: '101000004',
          busName: '7475',
          busOrder: 1,
        },
        {
          direction: 'KT광화문지사',
          firstArrivalBusTime: 0,
          secondArrivalBusTime: 0,
          firstArrivalBusCrowding: 'NODATA',
          secondArrivalBusCrowding: 'NODATA',
          firstArrivalTimeBefore: 'NODATA',
          secondArrivalTimeBefore: 'NODATA',
          busId: '100100002',
          busName: '03',
          busOrder: 22,
        },
        {
          direction: 'KT광화문지사',
          firstArrivalBusTime: 0,
          secondArrivalBusTime: 0,
          firstArrivalBusCrowding: 'NODATA',
          secondArrivalBusCrowding: 'NODATA',
          firstArrivalTimeBefore: 'NODATA',
          secondArrivalTimeBefore: 'NODATA',
          busId: '106000002',
          busName: '04',
          busOrder: 7,
        },
        {
          direction: 'KT광화문지사',
          firstArrivalBusTime: 446,
          secondArrivalBusTime: 911,
          firstArrivalBusCrowding: 'EASYGOING',
          secondArrivalBusCrowding: 'EASYGOING',
          firstArrivalTimeBefore: '4번째 전',
          secondArrivalTimeBefore: '6번째 전',
          busId: '100100001',
          busName: '01A',
          busOrder: 15,
        },
        {
          direction: '종로1가',
          firstArrivalBusTime: 109,
          secondArrivalBusTime: 608,
          firstArrivalBusCrowding: 'EASYGOING',
          secondArrivalBusCrowding: 'EASYGOING',
          firstArrivalTimeBefore: 'NODATA',
          secondArrivalTimeBefore: '3번째 전',
          busId: '100100077',
          busName: '501',
          busOrder: 26,
        },
        {
          direction: 'KT광화문지사',
          firstArrivalBusTime: 260,
          secondArrivalBusTime: 1067,
          firstArrivalBusCrowding: 'EASYGOING',
          secondArrivalBusCrowding: 'EASYGOING',
          firstArrivalTimeBefore: '1번째 전',
          secondArrivalTimeBefore: '7번째 전',
          busId: '123000011',
          busName: '708',
          busOrder: 32,
        },
        {
          direction: 'KT광화문지사',
          firstArrivalBusTime: 0,
          secondArrivalBusTime: 0,
          firstArrivalBusCrowding: 'NODATA',
          secondArrivalBusCrowding: 'NODATA',
          firstArrivalTimeBefore: 'NODATA',
          secondArrivalTimeBefore: 'NODATA',
          busId: '117000002',
          busName: 'N51',
          busOrder: 40,
        },
        {
          direction: '종로1가',
          firstArrivalBusTime: 302,
          secondArrivalBusTime: 944,
          firstArrivalBusCrowding: 'EASYGOING',
          secondArrivalBusCrowding: 'EASYGOING',
          firstArrivalTimeBefore: '1번째 전',
          secondArrivalTimeBefore: '6번째 전',
          busId: '100100006',
          busName: '101',
          busOrder: 44,
        },
        {
          direction: '을지로입구역.광교',
          firstArrivalBusTime: 518,
          secondArrivalBusTime: 972,
          firstArrivalBusCrowding: 'EASYGOING',
          secondArrivalBusCrowding: 'EASYGOING',
          firstArrivalTimeBefore: '2번째 전',
          secondArrivalTimeBefore: '6번째 전',
          busId: '100100081',
          busName: '506',
          busOrder: 46,
        },
        {
          direction: 'KT광화문지사',
          firstArrivalBusTime: 897,
          secondArrivalBusTime: 1035,
          firstArrivalBusCrowding: 'EASYGOING',
          secondArrivalBusCrowding: 'EASYGOING',
          firstArrivalTimeBefore: '5번째 전',
          secondArrivalTimeBefore: '7번째 전',
          busId: '100100447',
          busName: '7016',
          busOrder: 46,
        },
        {
          direction: 'KT광화문지사',
          firstArrivalBusTime: 309,
          secondArrivalBusTime: 508,
          firstArrivalBusCrowding: 'EASYGOING',
          secondArrivalBusCrowding: 'EASYGOING',
          firstArrivalTimeBefore: '1번째 전',
          secondArrivalTimeBefore: '2번째 전',
          busId: '100100185',
          busName: '1711',
          busOrder: 47,
        },
        {
          direction: '종로1가',
          firstArrivalBusTime: 117,
          secondArrivalBusTime: 717,
          firstArrivalBusCrowding: 'EASYGOING',
          secondArrivalBusCrowding: 'EASYGOING',
          firstArrivalTimeBefore: 'NODATA',
          secondArrivalTimeBefore: '4번째 전',
          busId: '100100029',
          busName: '150',
          busOrder: 91,
        },
      ],
    },
  },
};
